<?php

/*

example:

$emoticons[]='a b c';

where:
a - smilie code
b - image in the list && image to display
c - image to display, if you want to display in chat a bigger image [optional]

space == separator
| and ~ cannot be used as smilie codes
duplicate smilie codes cause errors
emoticons from the array $aliases are displayed in chat but do not appear in the list of emoticons

*/

$emoticons=array();

$emoticons[]=':smile: smile.png';
$emoticons[]=':alien: alien.png';
$emoticons[]=':angry: angry.png';
$emoticons[]=':blush: blush.png';
$emoticons[]=':cash: cash.png';
$emoticons[]=':cheers: cheers.png';
$emoticons[]=':cool: cool.png';
$emoticons[]=':cry: cry.png';
$emoticons[]=':dizzy: dizzy.png';
$emoticons[]=':embr: embr.png';
$emoticons[]=':furious: furious.png';
$emoticons[]=':innocent: innocent.png';
$emoticons[]=':kiss: kiss.png';
$emoticons[]=':lol: lol.png';
$emoticons[]=':love: love.png';
$emoticons[]=':morecry: morecry.png';
$emoticons[]=':sad: sad.png';
$emoticons[]=':sick: sick.png';
$emoticons[]=':unsure: unsure.png';
$emoticons[]=':wink: wink.png';
$emoticons[]=':sun: sun.png';
$emoticons[]=':moon: moon.png';
$emoticons[]=':stars: stars.png';
$emoticons[]=':hearts: hearts.png';
$emoticons[]=':feet: feet.png';
$emoticons[]=':thumbdown: thumbdown.png';
$emoticons[]=':thumbup: thumbup.png';
$emoticons[]=':punch: punch.png';
$emoticons[]=':clap: clap.png';
$emoticons[]=':hand: hand.png';

$aliases=array();
$aliases[]=':) smile.png';
$aliases[]=':( sad.png';
$aliases[]=';-) wink.png';
$aliases[]=':-) smile.png';
$aliases[]=':-( sad.png';
$aliases[]='rofl lol.png';
?>